# -*- coding: utf-8 -*-
"""Studysaathi.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/19Vao7RERE2uxasOFLZLYpHZdde7dAmNq
"""



import google.generativeai as genai
genai.configure(api_key="AIzaSyAHIqS2uzZbQkEr-ASA1YSJcunDuibHf14") # Replace "YOUR_GEMINI_API_KEY" with your actual API key
model = genai.GenerativeModel("gemini-2.5-flash")

from PyPDF2 import PdfReader
def extract_pdf_text(pdf_file):
  text=""
  reader = PdfReader(pdf_file)
  for page in reader.pages:
    page_text=page.extract_text()
    if page_text:
      text += page_text
  return text

from docx import Document
def extract_docx_text(docx_file):
  doc = Documents(docx_file)
  text = ""
  for para in doc.paragraphs:
    text += para.text + "\n"
  return text

def generate_summary(text):
    prompt = f"""Analyize the notes and provide:
                 1.detailed Summary
                 2.Key Concepts
                 3.Important Formulas
                 4.Revision Notes
                 Notes:
                 {text}
                 """
    response = model.generate_content(prompt)
    return response.text

def generate_questions(text):
    prompt = f"""Analyize the notes and provide:
                 1.detailed Summary
                 2.Key Concepts
                 3.Important Formulas
                 4.Revision Notes
                 Notes:
                 {text}
                 """
    response = model.generate_content(prompt)
    return response.text

def generate_answers(text):
    prompt = f"""Analyize the notes: generate detailed answers for all important questionss.




                 Notes:
                 {text}"""
    response = model.generate_content(prompt)
    return response.text

def generate_mcqs(text):

    prompt = f"""
    Create 10 MCQs with:

    Question
    4 Options
    Correct Answer

    Notes:
    {text}
    """

    response = model.generate_content(prompt)

    return response.text

import streamlit as st
st.title("StudySaathi AI")
uploaded_file = st.file_uploader("Upload Notes", type=["pdf","docx","text"])

if uploaded_file:

    if uploaded_file.name.endswith(".pdf"):
        notes_text = extract_pdf_text(uploaded_file)

    elif uploaded_file.name.endswith(".docx"):
        notes_text = extract_docx_text(uploaded_file)

    else:
        notes_text = uploaded_file.read().decode()

if st.button("Generate Summary"):
    summary = generate_summary(notes_text)
    st.subheader("Summary")
    st.write(summary)

if st.button("Generate Questions"):
    questions = generate_questions(notes_text)
    st.subheader("Questions")
    st.write(questions)

if st.button("Generate Answers"):
    answers = generate_answers(notes_text)
    st.subheader("Answers")
    st.write(answers)

if st.button("Generate MCQs"):
    mcqs = generate_mcqs(notes_text)
    st.subheader("MCQs")
    st.write(mcqs)
